return {
    print, --1
    warn, --2
    hookfunction, --3
    setmetatable, --4
    setclipboard, --5
    pcall, --6
    pairs, --7
    math.random, --8
    newcclosure, --9
    error, --10
    getnamecallmethod, --11
    string.format, --12
    string.gsub, --13
    string.match, --14
    appendfile, --15
    type, --16
    xpcall, --17
    assert, --18
    wait, --19
    spawn, --20
    getrawmetatable, --21
    old, --22
    task.wait, --23
    require, --24
    Vector2.new, --25
    CFrame.new, --26
    UDim2.new, --27
    unpack, --28
    task.spawn, --29
    table.insert, --30
    tonumber, --31
    tostring, --32
    os.date, --33
    sethiddenproperty, --34
    Instance.new, --35
    Color3.fromRGB, --36
    getupvalues, --37
    debug.getupvalue, --38
    math.floor, --39
    loadstring, --40
    request, --41
    encode, --42
    cancel, --43
    tick, --44
    typeof, --45
    new, --46
    getconnections, --47
    makefolder, --48
    isfolder, --49
    isfile, --50
    readfile, --51
    delfile, --52
    listfiles, --53
    loadfile, --54
    appendfile, --55
    writefile, --56
    Vector3.new, --57
    coroutine.wrap, --58
    fireclickdetector, --59
    fireproximityprompt, --60
    table.concat, --61
    string.sub, --62
    string.len, --63
    Function, --64
    Enable, --65
    Fire, --66
    string.find, --67
    table.find --68
}
